title: Andrei Nistor
email: you@example.com
description: >-
  Technical Artist and Game Developer. Tools, workflows, blog posts, and resume.
baseurl: "/ian_mywebsite"
url: "https://ianistor.github.io"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
collections:
  tools:
    output: true
    permalink: /tools/:name/
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: tools
    values:
      layout: tool
  - scope:
      path: ""
      type: projects
    values:
      layout: project
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Tools
    url: /tools/
  - title: Projects
    url: /projects/
  - title: Resume
    url: /cv/