title: My Technical Artist Blog
description: Tools and posts by a Technical Artist
baseurl: "/ian_mywebsite"
url: "https://ianistor.github.io"
collections:
  tools:
    output: true
permalink: pretty
